export interface EventInfo {
  id: string
  title: string
  description: string
  image: string
  date: string
  location: string
  organizer: string
  capacity: number
  tags: string[]
  status: 'upcoming' | 'ongoing' | 'completed'
}

export const eventInfo: EventInfo = {
  id: 'university-open-day-2025',
  title: 'University of Gecko Open Day 2025',
  description: 'Join us for our biggest open day of the year! Experience university life, meet academics and current students, tour our world-class facilities, and discover the perfect course for your future. With over 60 sessions across two days, there\'s something for everyone.\n\nOur open day offers a unique opportunity to explore our state-of-the-art campus, including our award-winning library, cutting-edge laboratories, and modern student accommodation. You\'ll have the chance to attend subject-specific taster sessions, meet with academic staff, and learn about our industry connections and career support services.\n\nWhether you\'re interested in Computer Science, Medicine, Business, Arts, or any of our other 50+ degree programs, our open day will help you make an informed decision about your university journey. Current students will be on hand to share their experiences, and our admissions team will be available to answer questions about applications, scholarships, and student finance.',
  image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9e1?w=1200&h=400&fit=crop',
  date: 'June 14-15, 2025',
  location: 'University of Gecko Campus',
  organizer: 'University of Gecko',
  capacity: 2000,
  tags: ['Open Day', 'University', 'Education', 'Campus Tour'],
  status: 'upcoming'
}

export interface Event {
  id: number
  title: string
  date: string
  time: string
  location: string
  attendees: number
  waitlistSpaces?: number
  price: string
  category: string
  description?: string
  image?: string
  tags?: string[]
  type?: string
}

export const events: Event[] = [
  {
    id: 1,
    title: "Welcome Talk",
    date: "2025-06-14",
    time: "9:30 AM - 10:00 AM",
    location: "Main Lecture Theatre",
    attendees: 0,
    price: "Free",
    category: "General",
    description: "Kick off the Open Day with a welcome from the Vice-Chancellor and an overview of the day's events.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop",
    tags: ["Welcome", "General"],
    type: "On Campus"
  },
  {
    id: 2,
    title: "Campus Tour",
    date: "2025-06-14",
    time: "10:15 AM - 11:15 AM",
    location: "Student Union Entrance",
    attendees: 60,
    price: "Free",
    category: "Tour",
    description: "Join our student ambassadors for a guided tour of the campus facilities and key locations.",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=400&h=250&fit=crop",
    tags: ["Tour", "Campus"],
    type: "On Campus"
  },
  {
    id: 3,
    title: "Accommodation Tour",
    date: "2025-06-14",
    time: "11:30 AM - 12:00 PM",
    location: "Halls of Residence Foyer",
    attendees: 40,
    price: "Free",
    category: "Tour",
    description: "See inside our student accommodation and learn about living on campus.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    tags: ["Accommodation", "Tour"],
    type: "On Campus"
  },
  {
    id: 4,
    title: "Subject Taster: Computer Science",
    date: "2025-06-14",
    time: "1:00 PM - 2:00 PM",
    location: "Science Building, Room 101",
    attendees: 0,
    price: "Free",
    category: "Subject Taster",
    description: "Experience a real university lecture and meet our Computer Science academics.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Computer Science"],
    type: "On Campus"
  },
  {
    id: 5,
    title: "Student Life Q&A",
    date: "2025-06-14",
    time: "2:15 PM - 3:00 PM",
    location: "Student Union Lounge",
    attendees: 100,
    price: "Free",
    category: "Q&A",
    description: "Ask current students about their experiences and get tips for making the most of university life.",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=250&fit=crop",
    tags: ["Q&A", "Student Life"],
    type: "On Campus"
  },
  {
    id: 6,
    title: "Virtual Open Day Overview",
    date: "2025-06-14",
    time: "3:15 PM - 4:00 PM",
    location: "Online (Zoom)",
    attendees: 0,
    waitlistSpaces: 20,
    price: "Free",
    category: "General",
    description: "Join our virtual session for an overview of the university and a live Q&A.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop",
    tags: ["Virtual", "General"],
    type: "Online"
  },
  {
    id: 7,
    title: "Meet the Academics: Humanities",
    date: "2025-06-15",
    time: "10:00 AM - 11:00 AM",
    location: "Humanities Building, Room 201",
    attendees: 25,
    price: "Free",
    category: "Meet the Academics",
    description: "Chat with lecturers from the Humanities department and ask your questions.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop",
    tags: ["Humanities", "Academics"],
    type: "On Campus"
  },
  {
    id: 8,
    title: "Subject Taster: Psychology",
    date: "2025-06-15",
    time: "11:15 AM - 12:00 PM",
    location: "Psychology Building, Room 110",
    attendees: 30,
    price: "Free",
    category: "Subject Taster",
    description: "Take part in a mini-lecture and interactive session with our Psychology team.",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Psychology"],
    type: "On Campus"
  },
  {
    id: 9,
    title: "Parents' Information Session",
    date: "2025-06-15",
    time: "12:15 PM - 1:00 PM",
    location: "Main Lecture Theatre",
    attendees: 80,
    price: "Free",
    category: "Parents",
    description: "A session for parents and guardians to learn about support, finance, and student welfare.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Parents", "Support"],
    type: "On Campus"
  },
  {
    id: 10,
    title: "Sports Centre Tour",
    date: "2025-06-15",
    time: "1:15 PM - 2:00 PM",
    location: "Sports Centre Reception",
    attendees: 50,
    price: "Free",
    category: "Tour",
    description: "Tour our sports facilities and find out about clubs and societies.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=250&fit=crop",
    tags: ["Sports", "Tour"],
    type: "On Campus"
  },
  {
    id: 11,
    title: "Subject Taster: Law",
    date: "2025-06-14",
    time: "10:30 AM - 11:15 AM",
    location: "Law Building, Room 12",
    attendees: 40,
    price: "Free",
    category: "Subject Taster",
    description: "Experience a taster lecture in Law and meet our Law faculty.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Law"],
    type: "On Campus"
  },
  {
    id: 12,
    title: "Admissions & Finance Talk",
    date: "2025-06-14",
    time: "11:30 AM - 12:15 PM",
    location: "Main Lecture Theatre",
    attendees: 120,
    price: "Free",
    category: "Admissions",
    description: "Learn about the admissions process, student finance, and scholarships.",
    image: "https://images.unsplash.com/photo-1503676382389-4809596d5290?w=400&h=250&fit=crop",
    tags: ["Admissions", "Finance"],
    type: "On Campus"
  },
  {
    id: 13,
    title: "Subject Taster: Business Management",
    date: "2025-06-14",
    time: "12:30 PM - 1:15 PM",
    location: "Business School, Room 3",
    attendees: 45,
    price: "Free",
    category: "Subject Taster",
    description: "Sample a Business Management lecture and meet our staff.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Business"],
    type: "On Campus"
  },
  {
    id: 14,
    title: "Library Tour",
    date: "2025-06-14",
    time: "1:30 PM - 2:00 PM",
    location: "Library Entrance",
    attendees: 30,
    price: "Free",
    category: "Tour",
    description: "Tour our award-winning library and discover its resources.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Library", "Tour"],
    type: "On Campus"
  },
  {
    id: 15,
    title: "Subject Taster: Engineering",
    date: "2025-06-14",
    time: "2:15 PM - 3:00 PM",
    location: "Engineering Building, Lab 2",
    attendees: 25,
    price: "Free",
    category: "Subject Taster",
    description: "Get hands-on in our Engineering labs and meet the team.",
    image: "https://images.unsplash.com/photo-1503676382389-4809596d5290?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Engineering"],
    type: "On Campus"
  },
  {
    id: 16,
    title: "International Student Information Session",
    date: "2025-06-14",
    time: "3:15 PM - 4:00 PM",
    location: "Online (Teams)",
    attendees: 0,
    waitlistSpaces: 10,
    price: "Free",
    category: "International",
    description: "Information and Q&A for international applicants.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["International", "Online"],
    type: "Online"
  },
  {
    id: 17,
    title: "Subject Taster: Medicine",
    date: "2025-06-14",
    time: "4:15 PM - 5:00 PM",
    location: "Medical School, Lecture Theatre A",
    attendees: 0,
    price: "Free",
    category: "Subject Taster",
    description: "Find out what it's like to study Medicine at our university.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Medicine"],
    type: "On Campus"
  },
  {
    id: 18,
    title: "Societies & Clubs Fair",
    date: "2025-06-14",
    time: "5:15 PM - 6:00 PM",
    location: "Student Union Hall",
    attendees: 100,
    price: "Free",
    category: "Societies",
    description: "Meet representatives from our many student societies and clubs.",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=250&fit=crop",
    tags: ["Societies", "Clubs"],
    type: "On Campus"
  },
  {
    id: 19,
    title: "Subject Taster: Mathematics",
    date: "2025-06-15",
    time: "9:00 AM - 9:45 AM",
    location: "Mathematics Building, Room 5",
    attendees: 30,
    price: "Free",
    category: "Subject Taster",
    description: "Enjoy a taster session in Mathematics with our academic team.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Mathematics"],
    type: "On Campus"
  },
  {
    id: 20,
    title: "Careers & Employability Talk",
    date: "2025-06-15",
    time: "10:00 AM - 10:45 AM",
    location: "Careers Centre",
    attendees: 50,
    price: "Free",
    category: "Careers",
    description: "Find out how we support your career ambitions and employability.",
    image: "https://images.unsplash.com/photo-1503676382389-4809596d5290?w=400&h=250&fit=crop",
    tags: ["Careers", "Employability"],
    type: "On Campus"
  },
  {
    id: 21,
    title: "Subject Taster: Chemistry",
    date: "2025-06-15",
    time: "11:00 AM - 11:45 AM",
    location: "Chemistry Building, Lab 1",
    attendees: 25,
    price: "Free",
    category: "Subject Taster",
    description: "Participate in a Chemistry taster session and meet our staff.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Chemistry"],
    type: "On Campus"
  },
  {
    id: 22,
    title: "Drop-in Q&A: Student Support",
    date: "2025-06-15",
    time: "12:00 PM - 12:45 PM",
    location: "Student Support Centre",
    attendees: 20,
    price: "Free",
    category: "Support",
    description: "Drop in to ask about student support, wellbeing, and disability services.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Support", "Q&A"],
    type: "On Campus"
  },
  {
    id: 23,
    title: "Subject Taster: English Literature",
    date: "2025-06-15",
    time: "1:00 PM - 1:45 PM",
    location: "Humanities Building, Room 105",
    attendees: 30,
    price: "Free",
    category: "Subject Taster",
    description: "Sample a lecture in English Literature and meet our staff.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "English"],
    type: "On Campus"
  },
  {
    id: 24,
    title: "Subject Taster: Physics",
    date: "2025-06-15",
    time: "2:00 PM - 2:45 PM",
    location: "Physics Building, Lab 3",
    attendees: 25,
    price: "Free",
    category: "Subject Taster",
    description: "Experience a Physics taster session and tour our labs.",
    image: "https://images.unsplash.com/photo-1503676382389-4809596d5290?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Physics"],
    type: "On Campus"
  },
  {
    id: 25,
    title: "Accommodation Drop-in",
    date: "2025-06-15",
    time: "3:00 PM - 3:45 PM",
    location: "Halls of Residence Foyer",
    attendees: 40,
    price: "Free",
    category: "Accommodation",
    description: "Drop in to view accommodation and ask questions about living on campus.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    tags: ["Accommodation", "Drop-in"],
    type: "On Campus"
  },
  {
    id: 26,
    title: "Subject Taster: Economics",
    date: "2025-06-15",
    time: "4:00 PM - 4:45 PM",
    location: "Business School, Room 7",
    attendees: 35,
    price: "Free",
    category: "Subject Taster",
    description: "Join our Economics team for a taster session and Q&A.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Economics"],
    type: "On Campus"
  },
  {
    id: 27,
    title: "Sports Demo: Rowing Club",
    date: "2025-06-15",
    time: "5:00 PM - 5:45 PM",
    location: "Sports Centre Lawn",
    attendees: 20,
    price: "Free",
    category: "Sports",
    description: "Watch a demonstration by the Rowing Club and learn how to get involved.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=250&fit=crop",
    tags: ["Sports", "Demo"],
    type: "On Campus"
  },
  {
    id: 28,
    title: "Virtual Drop-in: Admissions",
    date: "2025-06-15",
    time: "6:00 PM - 6:45 PM",
    location: "Online (Zoom)",
    attendees: 0,
    waitlistSpaces: 10,
    price: "Free",
    category: "Admissions",
    description: "Drop in virtually to ask about admissions and application process.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop",
    tags: ["Admissions", "Virtual"],
    type: "Online"
  },
  {
    id: 29,
    title: "Subject Taster: Politics",
    date: "2025-06-15",
    time: "7:00 PM - 7:45 PM",
    location: "Humanities Building, Room 210",
    attendees: 25,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Politics at university with our academic team.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Politics"],
    type: "On Campus"
  },
  {
    id: 30,
    title: "Subject Taster: Art & Design",
    date: "2025-06-15",
    time: "8:00 PM - 8:45 PM",
    location: "Art Studio, Room 2",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Participate in a creative Art & Design session.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Art"],
    type: "On Campus"
  },
  {
    id: 31,
    title: "Wellbeing & Mindfulness Workshop",
    date: "2025-06-15",
    time: "9:00 PM - 9:45 PM",
    location: "Student Support Centre",
    attendees: 30,
    price: "Free",
    category: "Wellbeing",
    description: "Join our wellbeing team for a mindfulness and relaxation workshop.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Wellbeing", "Workshop"],
    type: "On Campus"
  },
  {
    id: 32,
    title: "Virtual Open Day Wrap-up",
    date: "2025-06-15",
    time: "10:00 PM - 10:30 PM",
    location: "Online (Teams)",
    attendees: 0,
    waitlistSpaces: 15,
    price: "Free",
    category: "General",
    description: "Join us online for a final Q&A and wrap-up of the Open Day.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop",
    tags: ["Virtual", "Wrap-up"],
    type: "Online"
  },
  {
    id: 33,
    title: "Subject Taster: Environmental Science",
    date: "2025-06-14",
    time: "10:15 AM - 11:00 AM",
    location: "Environmental Science Lab",
    attendees: 28,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Environmental Science with hands-on activities.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Environment"],
    type: "On Campus"
  },
  {
    id: 34,
    title: "Subject Taster: Sociology",
    date: "2025-06-14",
    time: "10:15 AM - 11:00 AM",
    location: "Sociology Building, Room 2",
    attendees: 32,
    price: "Free",
    category: "Subject Taster",
    description: "Join a Sociology taster session and meet the team.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Sociology"],
    type: "On Campus"
  },
  {
    id: 35,
    title: "Subject Taster: Philosophy",
    date: "2025-06-14",
    time: "11:30 AM - 12:15 PM",
    location: "Philosophy Seminar Room",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Debate big questions in our Philosophy taster.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Philosophy"],
    type: "On Campus"
  },
  {
    id: 36,
    title: "Subject Taster: Modern Languages",
    date: "2025-06-14",
    time: "11:30 AM - 12:15 PM",
    location: "Languages Centre, Room 4",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Try a mini-lesson in French, Spanish, or German.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Languages"],
    type: "On Campus"
  },
  {
    id: 37,
    title: "Subject Taster: Drama",
    date: "2025-06-14",
    time: "1:00 PM - 2:00 PM",
    location: "Drama Studio",
    attendees: 22,
    price: "Free",
    category: "Subject Taster",
    description: "Take part in a Drama workshop with our students.",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Drama"],
    type: "On Campus"
  },
  {
    id: 38,
    title: "Subject Taster: Geography",
    date: "2025-06-14",
    time: "1:00 PM - 2:00 PM",
    location: "Geography Building, Room 8",
    attendees: 27,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Geography at university level.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Geography"],
    type: "On Campus"
  },
  {
    id: 39,
    title: "Subject Taster: Criminology",
    date: "2025-06-14",
    time: "2:15 PM - 3:00 PM",
    location: "Criminology Lab",
    attendees: 24,
    price: "Free",
    category: "Subject Taster",
    description: "Discover the world of Criminology.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Criminology"],
    type: "On Campus"
  },
  {
    id: 40,
    title: "Subject Taster: Education",
    date: "2025-06-14",
    time: "2:15 PM - 3:00 PM",
    location: "Education Building, Room 6",
    attendees: 26,
    price: "Free",
    category: "Subject Taster",
    description: "Find out about studying Education at university.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Education"],
    type: "On Campus"
  },
  {
    id: 41,
    title: "Subject Taster: Music",
    date: "2025-06-14",
    time: "3:15 PM - 4:00 PM",
    location: "Music Studio",
    attendees: 15,
    price: "Free",
    category: "Subject Taster",
    description: "Join a Music taster session and meet our staff.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Music"],
    type: "On Campus"
  },
  {
    id: 42,
    title: "Subject Taster: Nursing",
    date: "2025-06-14",
    time: "3:15 PM - 4:00 PM",
    location: "Nursing Skills Lab",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Experience a Nursing skills session.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Nursing"],
    type: "On Campus"
  },
  {
    id: 43,
    title: "Subject Taster: Architecture",
    date: "2025-06-14",
    time: "4:15 PM - 5:00 PM",
    location: "Architecture Studio",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Try your hand at Architecture with our team.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Architecture"],
    type: "On Campus"
  },
  {
    id: 44,
    title: "Subject Taster: Media Studies",
    date: "2025-06-14",
    time: "4:15 PM - 5:00 PM",
    location: "Media Suite",
    attendees: 22,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Media Studies and our facilities.",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Media"],
    type: "On Campus"
  },
  {
    id: 45,
    title: "Subject Taster: History",
    date: "2025-06-15",
    time: "9:00 AM - 9:45 AM",
    location: "History Building, Room 1",
    attendees: 30,
    price: "Free",
    category: "Subject Taster",
    description: "Join a History taster session and meet our staff.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "History"],
    type: "On Campus"
  },
  {
    id: 46,
    title: "Subject Taster: Biomedical Science",
    date: "2025-06-15",
    time: "9:00 AM - 9:45 AM",
    location: "Biomedical Lab",
    attendees: 28,
    price: "Free",
    category: "Subject Taster",
    description: "Experience Biomedical Science in our labs.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Biomedical"],
    type: "On Campus"
  },
  {
    id: 47,
    title: "Subject Taster: Marketing",
    date: "2025-06-15",
    time: "10:00 AM - 10:45 AM",
    location: "Business School, Room 8",
    attendees: 0,
    price: "Free",
    category: "Subject Taster",
    description: "Discover Marketing at university level.",
    image: "https://images.unsplash.com/photo-1503676382389-4809596d5290?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Marketing"],
    type: "On Campus"
  },
  {
    id: 48,
    title: "Subject Taster: Social Work",
    date: "2025-06-15",
    time: "10:00 AM - 10:45 AM",
    location: "Social Work Centre",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Learn about Social Work and our placements.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Social Work"],
    type: "On Campus"
  },
  {
    id: 49,
    title: "Subject Taster: Fine Art",
    date: "2025-06-15",
    time: "11:00 AM - 11:45 AM",
    location: "Art Studio, Room 5",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Participate in a Fine Art taster session.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Fine Art"],
    type: "On Campus"
  },
  {
    id: 50,
    title: "Subject Taster: Journalism",
    date: "2025-06-15",
    time: "11:00 AM - 11:45 AM",
    location: "Journalism Suite",
    attendees: 22,
    price: "Free",
    category: "Subject Taster",
    description: "Try your hand at Journalism in our newsroom.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Journalism"],
    type: "On Campus"
  },
  {
    id: 51,
    title: "Subject Taster: Classics",
    date: "2025-06-15",
    time: "12:00 PM - 12:45 PM",
    location: "Classics Seminar Room",
    attendees: 16,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Classics with our academic team.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Classics"],
    type: "On Campus"
  },
  {
    id: 52,
    title: "Subject Taster: Linguistics",
    date: "2025-06-15",
    time: "12:00 PM - 12:45 PM",
    location: "Linguistics Lab",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Discover Linguistics and language science.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Linguistics"],
    type: "On Campus"
  },
  {
    id: 53,
    title: "Subject Taster: Film Studies",
    date: "2025-06-15",
    time: "1:00 PM - 1:45 PM",
    location: "Film Theatre",
    attendees: 24,
    price: "Free",
    category: "Subject Taster",
    description: "Experience Film Studies at university level.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Film"],
    type: "On Campus"
  },
  {
    id: 54,
    title: "Subject Taster: Anthropology",
    date: "2025-06-15",
    time: "1:00 PM - 1:45 PM",
    location: "Anthropology Lab",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Join our Anthropology team for a taster session.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Anthropology"],
    type: "On Campus"
  },
  {
    id: 55,
    title: "Subject Taster: Computer Science (AI)",
    date: "2025-06-15",
    time: "2:00 PM - 2:45 PM",
    location: "Science Building, Room 102",
    attendees: 0,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Artificial Intelligence in Computer Science.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "AI"],
    type: "On Campus"
  },
  {
    id: 56,
    title: "Subject Taster: Business Analytics",
    date: "2025-06-15",
    time: "2:00 PM - 2:45 PM",
    location: "Business School, Room 9",
    attendees: 22,
    price: "Free",
    category: "Subject Taster",
    description: "Discover Business Analytics and its applications.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Analytics"],
    type: "On Campus"
  },
  {
    id: 57,
    title: "Subject Taster: Law (Moot Court)",
    date: "2025-06-15",
    time: "3:00 PM - 3:45 PM",
    location: "Law Building, Moot Court",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Participate in a Law moot court session.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Law"],
    type: "On Campus"
  },
  {
    id: 58,
    title: "Subject Taster: Psychology (Neuroscience)",
    date: "2025-06-15",
    time: "3:00 PM - 3:45 PM",
    location: "Psychology Building, Room 120",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Neuroscience in our Psychology taster.",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Neuroscience"],
    type: "On Campus"
  },
  {
    id: 59,
    title: "Subject Taster: Education (Primary)",
    date: "2025-06-15",
    time: "4:00 PM - 4:45 PM",
    location: "Education Building, Room 8",
    attendees: 22,
    price: "Free",
    category: "Subject Taster",
    description: "Learn about Primary Education at university.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Primary"],
    type: "On Campus"
  },
  {
    id: 60,
    title: "Subject Taster: Engineering (Robotics)",
    date: "2025-06-15",
    time: "4:00 PM - 4:45 PM",
    location: "Engineering Building, Lab 4",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Experience Robotics in our Engineering taster.",
    image: "https://images.unsplash.com/photo-1503676382389-4809596d5290?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Robotics"],
    type: "On Campus"
  },
  {
    id: 61,
    title: "Subject Taster: Business (Entrepreneurship)",
    date: "2025-06-15",
    time: "5:00 PM - 5:45 PM",
    location: "Business School, Room 10",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Entrepreneurship in Business.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Entrepreneurship"],
    type: "On Campus"
  },
  {
    id: 62,
    title: "Subject Taster: Computer Science (Cybersecurity)",
    date: "2025-06-15",
    time: "5:00 PM - 5:45 PM",
    location: "Science Building, Room 103",
    attendees: 20,
    price: "Free",
    category: "Subject Taster",
    description: "Learn about Cybersecurity in Computer Science.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Cybersecurity"],
    type: "On Campus"
  },
  {
    id: 63,
    title: "Subject Taster: Psychology (Forensics)",
    date: "2025-06-15",
    time: "6:00 PM - 6:45 PM",
    location: "Psychology Building, Room 130",
    attendees: 18,
    price: "Free",
    category: "Subject Taster",
    description: "Explore Forensic Psychology in this taster session.",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=250&fit=crop",
    tags: ["Subject Taster", "Forensics"],
    type: "On Campus"
  },
  {
    id: 64,
    title: "Virtual Open Day Social",
    date: "2025-06-15",
    time: "7:00 PM - 8:00 PM",
    location: "Online (Teams)",
    attendees: 0,
    waitlistSpaces: 20,
    price: "Free",
    category: "General",
    description: "Join our virtual social to meet staff and students and wrap up the event!",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop",
    tags: ["Virtual", "Social"],
    type: "Online"
  }
]

export const getCategoryColor = (category: string) => {
  const colors = {
    Technology: "bg-blue-100 text-blue-800",
    Networking: "bg-green-100 text-green-800",
    Design: "bg-purple-100 text-purple-800",
    Marketing: "bg-orange-100 text-orange-800",
    Product: "bg-pink-100 text-pink-800",
    Education: "bg-indigo-100 text-indigo-800",
    Business: "bg-emerald-100 text-emerald-800",
    Photography: "bg-amber-100 text-amber-800",
    Health: "bg-red-100 text-red-800"
  }
  return colors[category as keyof typeof colors] || "bg-gray-100 text-gray-800"
} 